name: release
on:
    workflow_dispatch:
permissions:
    # Provenance generation in GitHub Actions requires "write" access to the "id-token"
    id-token: write

jobs:
    release:
        name: Release
        environment: npm
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: "20"
                  cache: "pnpm"
                  registry-url: "https://registry.npmjs.org"
            # Update npm to the latest version to enable OIDC
            - name: Update npm
              run: |
                  npm install -g npm@latest
                  npm --version
            - run: pnpm install
            - run: npm run build
            - run: npm publish
